[package]
name = "soroban-tools"
description = "Soroban Tools"
homepage = "https://github.com/stellar/soroban-cli"
repository = "https://github.com/stellar/soroban-cli"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
readme = "README.md"
version = "0.2.1"
edition = "2021"
rust-version = "1.65"
autobins = false
build = "build.rs"

[build-dependencies]
crate-git-revision = "0.0.2"

[[bin]]
name = "soroban"
path = "cmd/soroban-cli/src/main.rs"

[dependencies]
soroban-env-host = { workspace = true, features = ["vm", "serde", "hostfn_log_fmt_values"] }
soroban-spec = { workspace = true }
soroban-token-spec = { workspace = true }
stellar-strkey = { workspace = true }
clap = { version = "3.1.18", features = ["derive", "env"] }
base64 = "0.13.0"
thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
hex = "0.4.3"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
clap_complete = "3.2.3"
rand = "0.8.5"
wasmparser = "0.90.0"
sha2 = "0.10.6"
csv = "1.1.6"
ed25519-dalek = "1.0.1"
jsonrpsee-http-client = "0.15.1"
jsonrpsee-core = "0.15.1"
regex = "1.6.0"
wasm-opt = "0.110.1"

[dev_dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"

[workspace]
members = [
    "cmd/soroban-cli",
    "cmd/soroban-cli/tests/fixtures/test-wasms/hello_world",
    "cmd/soroban-cli/tests/fixtures/test-wasms/invoker_account_exists",
]
default-members = ["cmd/soroban-cli"]

[workspace.dependencies.soroban-env-host]
version = "0.0.10"
git = "https://github.com/stellar/rs-soroban-env"
rev = "c148051"

[workspace.dependencies.soroban-spec]
version = "0.3.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "501379d"

[workspace.dependencies.soroban-token-spec]
version = "0.3.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "501379d"

[workspace.dependencies.soroban-sdk]
version = "0.3.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "501379d"

[workspace.dependencies.stellar-strkey]
version = "0.0.6"
git = "https://github.com/stellar/rs-stellar-strkey"
rev = "5e582a8"

# [patch."https://github.com/stellar/rs-soroban-env"]
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host/" }
# [patch."https://github.com/stellar/rs-soroban-sdk"]
# soroban-spec = { path = "../rs-soroban-sdk/soroban-spec/" }
# soroban-token-spec = { path = "../rs-soroban-sdk/soroban-token-spec/" }
# soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk/" }
# [patch."https://github.com/stellar/rs-stellar-xdr"]
# stellar-xdr = { path = "../rs-stellar-xdr/" }

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
